<li>
                            <div class="HistoryImg">
                                <a href="[field:arcurl/]" target="_blank"><img
                                        src="[field:picname/]"></a>
                            </div>
                            <div class="HistoryInfo">
                                <h2><a href="[field:arcurl/]">[field:title/]...</a></h2>

                            </div>
                        </li>