<li>
                        <div class="newsTitle">
                            <h2><a href="[field:arcurl/]"
                                   target="_blank">[field:title/]</a></h2>
                            <div class="newsTitletag">
                                <span>浏览量：[field:click/] </span>
                            </div>
                        </div>

                        <div class="newsTxt">
                            <div class="newsTxtImg"><img src="[field:picname/]"></div>
                            <div class="newsTxtInfo">
                                <div class="newsTag">
                                    <span>[field:pubdate function="GetDateTimeMK(@me)" /]</span>
                                </div>
                                <div class="newsview">
                                    [field:description function="cn_substr(@me,130)"/]...
                                    <a href="[field:arcurl/]" title="[field:title/]"
                                       target="_blank">[详情]</a>
                                </div>
                            </div>
                        </div>

                    </li>