<li>
                            <div class="HistoryImg">
                                <a href="[field:arcurl/]" target="_blank"><img
                                        src="{dede:global.cfg_templets_skin/}/img/574eb19c345ae.jpg"></a>
                            </div>
                            <div class="HistoryInfo">
                                <h2><a href="[field:arcurl/]">[field:title/]</a></h2>

                            </div>
                        </li>