<?php
$z[0]=Array("arcurl","",65,80);
$z[1]=Array("title","",89,103);
$z[2]=Array("title","",156,170);
$z[3]=Array("click","",285,299);
$z[4]=Array("picname","",483,499);
$z[5]=Array("pubdate","",658,705);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",843,893);
$z[6][4]['function']="cn_substr(@me,130)";
$z[7]=Array("arcurl","",942,957);
$z[8]=Array("title","",966,980);

?>