<?php
$z[0]=Array("global","",69,95);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",138,165);
$z[1][4]['name']="cfg_keywords";
$z[2]=Array("global","",207,237);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",347,379);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",438,470);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",704,731);
$z[5][4]['name']="cfg_indexurl";
$z[6]=Array("channel","\r\n						<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n						",756,962);
$z[6][4]['row']="4";
$z[6][4]['type']="top";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a> </li>";
$z[7]=Array("global","",1147,1171);
$z[7][4]['name']="cfg_beian";
$z[8]=Array("global","",8334,8366);
$z[8][4]['name']="cfg_templets_skin";
$z[9]=Array("global","",8444,8476);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("global","",8544,8576);
$z[10][4]['name']="cfg_templets_skin";
$z[11]=Array("global","",8662,8694);
$z[11][4]['name']="cfg_templets_skin";
$z[12]=Array("global","",8764,8796);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",8868,8900);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("global","",8973,9005);
$z[14][4]['name']="cfg_templets_skin";
$z[15]=Array("global","",13176,13208);
$z[15][4]['name']="cfg_templets_skin";

?>